[package]
name = "sigimora-crypto"
description = "BLS signatures, Shamir SSS, Pedersen VSS, Pedersen DKG, and BLS Threshold Signing for SIGIMORA"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
sigimora-math = { path = "../sigimora-math" }
blstrs = { workspace = true }
ff = { workspace = true }
group = { workspace = true }
serde = { workspace = true }
zeroize = { workspace = true }
subtle = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
aes-gcm = { workspace = true }
hex = { workspace = true }
hkdf = { workspace = true }
